# Generated by Django 4.1.1 on 2022-09-29 13:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_answerlist_alter_answer_answers_delete_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.section')),
            ],
            bases=('modules.section',),
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.section')),
            ],
            bases=('modules.section',),
        ),
        migrations.CreateModel(
            name='ModuleProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Module ordering',
                'verbose_name_plural': 'Module Ordering',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modules.module',),
        ),
        migrations.AlterModelOptions(
            name='input',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['ordering']},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answers',
            new_name='answer_list',
        ),
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
        migrations.RemoveField(
            model_name='section',
            name='uri',
        ),
        migrations.AddField(
            model_name='input',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answerlist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='input',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='rules',
            field=models.CharField(default='true', max_length=255),
        ),
        migrations.CreateModel(
            name='ImageSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.section')),
                ('uri', models.CharField(blank=True, max_length=255)),
            ],
            bases=('modules.section',),
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.section')),
                ('uri', models.CharField(blank=True, max_length=255)),
            ],
            bases=('modules.section',),
        ),
        migrations.AlterField(
            model_name='answerlist',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_lists', to='modules.formsection'),
        ),
        migrations.AlterField(
            model_name='input',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='modules.formsection'),
        ),
    ]
