# Generated by Django 4.1.1 on 2022-09-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_title_page_title_alter_section_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answers',
            new_name='answer_list',
        ),
    ]
