# Generated by Django 4.1.1 on 2022-10-04 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_formsection_textsection_moduleproxy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
