# Generated by Django 4.1.1 on 2022-10-11 08:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_module_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='module',
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('min_duration', models.IntegerField(default=0, help_text='Minimum time in hours before the user can go to the next part')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='modules.module')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='PartProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Part ordering',
                'verbose_name_plural': 'Parts Ordering',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modules.part',),
        ),
        migrations.AddField(
            model_name='page',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='modules.part'),
            preserve_default=False,
        ),
    ]
