# Generated by Django 4.1.1 on 2022-09-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_rename_answers_answer_answer_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.section')),
            ],
            bases=('modules.section',),
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.section')),
            ],
            bases=('modules.section',),
        ),
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
        migrations.RemoveField(
            model_name='section',
            name='uri',
        ),
        migrations.CreateModel(
            name='ImageSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.section')),
                ('uri', models.CharField(blank=True, max_length=255)),
            ],
            bases=('modules.section',),
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.section')),
                ('uri', models.CharField(blank=True, max_length=255)),
            ],
            bases=('modules.section',),
        ),
        migrations.AlterField(
            model_name='answerlist',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_lists', to='modules.formsection'),
        ),
        migrations.AlterField(
            model_name='input',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='modules.formsection'),
        ),
    ]
