# Generated by Django 4.1.1 on 2022-09-29 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_formsection_textsection_remove_section_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Module ordering',
                'verbose_name_plural': 'Module Ordering',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modules.module',),
        ),
        migrations.AlterModelOptions(
            name='input',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='input',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answerlist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='input',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
