# Generated by Django 4.1.1 on 2022-10-13 08:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_create_module_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='rules',
        ),
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='modules.input')),
                ('section', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='modules.section')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comparator', models.CharField(choices=[('==', 'Equals'), ('!=', 'Not equals'), ('>', 'Greater than'), ('<', 'Less than'), ('>=', 'Greater or equals'), ('<=', 'Less or equals')], max_length=2)),
                ('value', models.CharField(max_length=255)),
                ('should_be', models.BooleanField(default=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='modules.input')),
                ('rule_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='modules.rulegroup')),
            ],
        ),
    ]
