# Generated by Django 4.1.1 on 2022-10-25 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_add_rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleProxy',
        ),
        migrations.AlterField(
            model_name='answer',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='modules.input'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='comparator',
            field=models.CharField(choices=[('eq', 'Equals'), ('ne', 'Not equals'), ('gt', 'Greater than'), ('lt', 'Less than'), ('ge', 'Greater or equals'), ('le', 'Less or equals')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rule',
            name='should_be',
            field=models.BooleanField(default=True, verbose_name='Should be True'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
