# Generated by Django 4.1.1 on 2022-11-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_remove_input_value_alter_input_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartProxy',
        ),
    ]
