# Generated by Django 4.1.1 on 2022-11-03 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0009_delete_partproxy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerlist',
            unique_together={('section', 'user')},
        ),
    ]
