# Generated by Django 4.1.1 on 2022-11-15 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undefined', 'Undefined')], default='undefined', max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('relationshipstatus', models.CharField(choices=[('married', 'Married'), ('coliving', 'Coliving'), ('relationship', 'Relationship'), ('single', 'Single'), ('undefined', 'Undefined')], default='undefined', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='relationshipstatus',
        ),
    ]
