# Generated by Django 4.1.1 on 2022-11-20 16:31

from django.db import migrations
import somnus.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_remove_user_dateofbirth_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', somnus.users.models.SomnusUserManager()),
            ],
        ),
    ]
