# Generated by Django 4.1.1 on 2022-10-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_module_perms',
        ),
    ]
