# Generated by Django 4.1.1 on 2022-10-25 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepdiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='sleepdiary',
            name='started_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
