# Generated by Django 4.1.1 on 2022-11-03 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepdiary', '0002_alter_diaryentry_options_alter_diaryentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
