# Generated by Django 4.1.1 on 2022-11-03 14:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleepdiary', '0003_alter_diaryentry_date_alter_diaryentry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sleepdiary.sleepdiary'),
        ),
        migrations.CreateModel(
            name='SleepRestrictionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week', models.DateField(default=datetime.date(2022, 11, 3))),
                ('custom_rise_time', models.TimeField(default=datetime.time(7, 0, tzinfo=datetime.timezone.utc))),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=18000))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_restriction_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-week',),
                'unique_together': {('user', 'week')},
            },
        ),
    ]
