# Generated by Django 4.1.1 on 2022-11-08 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepdiary', '0004_alter_diaryentry_date_alter_diaryentry_diary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sleeprestrictionplan',
            name='week',
            field=models.DateField(default=datetime.date(2022, 11, 8)),
        ),
    ]
