# Generated by Django 4.1.1 on 2022-11-10 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepdiary', '0005_alter_diaryentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeprestrictionplan',
            name='week',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
