# Generated by Django 4.1.1 on 2022-11-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleepdiary', '0006_alter_sleeprestrictionplan_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleepdiary',
            options={'verbose_name_plural': 'Sleep diaries'},
        ),
    ]
